import { Button, VerticalBox } from "std-widgets.slint";
import { ActionsPanel } from "actions_panel.slint";
import { FormatSelector } from "format_selector.slint";
import { AlphaSettings } from "alpha_settings.slint";

export component ControlPanel inherits VerticalBox {
    in-out property <float> alpha-val: 1.0;
    in-out property <bool> use-alpha: false;
    in-out property <string> selected-format: "png";
    in property <bool> processing;
    in property <bool> has-files;

    callback add-pressed();
    callback run-pressed();
    callback clear-pressed();

    spacing: 20px;

    ActionsPanel {
        has-files: root.has-files;
        processing: root.processing;
        add-pressed => { root.add-pressed() }
        clear-pressed => { root.clear-pressed() }
    }

    FormatSelector {
        current-format <=> root.selected-format;
    }

    AlphaSettings {
        use-alpha <=> root.use-alpha;
        alpha-val <=> root.alpha-val;
    }

    Button {
        text: "Process Batch";
        primary: true;
        enabled: !root.processing && root.has-files;
        clicked => { root.run-pressed() }
    }
}
