name: Build Windows Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.editorconfig'
      - '.gitattributes'
      - '.gitignore'
      - 'LICENSE'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.editorconfig'
      - '.gitattributes'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build Binary
        run: cargo build --release --locked

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows_release
          path: target/release/slint-image-converter.exe
          if-no-files-found: error
